services:
  traefik:
    container_name: traefik
    image: traefik:v3
    restart: unless-stopped
    command: >
      --api=true
      --log.level=${LOG_LEVEL:-INFO}
      --accesslog=${ACCESS_LOG:-true}
      --providers.docker
      --providers.docker.exposedByDefault=false
      --providers.docker.network=proxy
      --entryPoints.http.address=":80"
      --entryPoints.https.address=":443"
      --entryPoints.http.http.redirections.entrypoint.to=https
      --entryPoints.http.http.redirections.entrypoint.scheme=https
      --entryPoints.https.http.tls.certresolver=internal-ca
      --certificatesResolvers.internal-ca.acme.tlsChallenge=true
      --certificatesResolvers.internal-ca.acme.email=admin@home.joe.nyland.io
      --certificatesresolvers.internal-ca.acme.caServer=https://ca.home.joe.nyland.io:9000/acme/acme/directory
      --certificatesResolvers.internal-ca.acme.storage=/letsencrypt/acme.json
      --certificatesResolvers.internal-ca.acme.httpChallenge=true
      --certificatesResolvers.internal-ca.acme.httpChallenge.entryPoint=http
      --serversTransport.rootCAs=/etc/ssl/certs/ca-certificates.crt
      --metrics.prometheus=true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    extra_hosts:
      host.docker.internal: 10.10.0.10
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`traefik`)
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.middlewares: trusted-ipallowlist, authentik
      traefik.http.middlewares.trusted-ipallowlist.ipallowlist.sourcerange: >
        2a00:23c8:bda0:b310::/64,
        2a00:23c8:bda0:b307::/64,
        fdff:0205:2005::/123,
        fd21:ae03:5023:1::/64,
        172.19.0.0/16,
        fd21:ae03:5023:8::/64,
        172.26.0.0/16
    environment:
      LEGO_CA_CERTIFICATES: /etc/ssl/certs/ca-certificates.crt
      LEGO_CA_SERVER_NAME: ca.home.joe.nyland.io
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - /containers/traefik/letsencrypt/acme.json:/letsencrypt/acme.json

networks:
  proxy:
    name: proxy
    enable_ipv6: true
