services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    command: >
      --api.insecure=true
      --providers.docker
      --providers.docker.exposedByDefault=false
      --entryPoints.HTTP.address=":80"
      --entryPoints.HTTPS.address=":443"
      --entryPoints.HTTP.http.redirections.entrypoint.to=HTTPS
      --entryPoints.HTTP.http.redirections.entrypoint.scheme=https
      --entryPoints.HTTPS.http.tls.certresolver=internal-ca
      --entryPoints.traefik.address=":8081"
      --certificatesResolvers.internal-ca.acme.tlsChallenge=true
      --certificatesResolvers.internal-ca.acme.email=admin@home.joe.nyland.io
      --certificatesresolvers.internal-ca.acme.caServer=https://ca.home.joe.nyland.io:9000/acme/acme/directory
      --certificatesResolvers.internal-ca.acme.storage=/letsencrypt/acme.json
      --certificatesResolvers.internal-ca.acme.httpChallenge=true
      --certificatesResolvers.internal-ca.acme.httpChallenge.entryPoint=HTTP
      --serversTransport.insecureSkipVerify=true
      --serversTransport.rootCAs=/usr/local/share/ca-certificates/ca.crt
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081" # The Web UI (enabled by --api.insecure=true)
    extra_hosts:
      - "host.docker.internal:2a00:23c8:bda0:b310::5"
      - "host.docker.internal:10.10.0.5"
    environment:
      LEGO_CA_CERTIFICATES: /usr/local/share/ca-certificates/ca.crt
      LEGO_CA_SERVER_NAME: ca.home.joe.nyland.io
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /containers/traefik/ca.crt:/usr/local/share/ca-certificates/ca.crt
      - /containers/traefik/letsencrypt/acme.json:/letsencrypt/acme.json
